//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tcc_windows_version.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string email {
            get {
                return ((string)(this["email"]));
            }
            set {
                this["email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string senha {
            get {
                return ((string)(this["senha"]));
            }
            set {
                this["senha"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAMWElEQVR4nO3dDVLrSBKFUZh4W2VVLJaOm" +
            "GmmjdvGf5IqM+85C+g2JVv5Vck83gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAACAX71bnp8+Pj4qvZxnfBV5He3fW5+fnwVeBcA+/mNdASCPAACAQAIAAAIJAAAIJAAAIJAAA" +
            "IBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAA" +
            "AgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAg" +
            "EACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAAC" +
            "PTuov/08fHxVen1sNQrnw/vo3ncL5v7/PxMX4IfnAAA3EfUMYoAALifCGAMAQAAgQQAwGOcAjCCAAB4n" +
            "AigPQEA8BwRQGsCAOB5IoC2BADAa0QALQkAgNeJANoRAADbEAG0IgAAtiMCaEMAAGxLBNCCAADYngigP" +
            "AEAAIEEAMA+nAJQmgAA2I8IoCwBALAvEUBJAgBgfyKAcgQAwDFEAKUIAIDjiADKEAAAxxIBlCAAAI4nA" +
            "lhOAACsIQJYSgAArCMCWEYAAKwlAlhCAACsJwI4nAAAgEACAKAGpwAcSgAA1CECOIwAAKhFBHAIAQBQj" +
            "whgd38sMUBJUyPgvcBriPcmAAA42LWwEQYHEwD/1v1NWGXX4MMMPOL83uUesjPfAQCgoi/fhdiXAACgM" +
            "iGwEwEAQAdCYGMCAIBOhMBGBAAAHYmAFwkAALoSAS8QAAB0JgKeJAAA6E4EPEEAADCBCHiQAABgChHwA" +
            "AEAwCQi4E4CAIBpRMAdBAAABBIAAEzkFOAGfw6YinxwAXbmBACAqWwmfiEAAJhMBFwhAAAgkAAAgEACA" +
            "IDpPAa4QAAAQCABAACBBAAACTwGOCMAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgk" +
            "AAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACC" +
            "QAACCQAACDQHxf9p8/Pz0ov52EfHx/vzV4yfW35XvvyPoBjCQDgliOi8tr/QxjATgQAcKraCdKl1yMKY" +
            "AMCALJ1fGR0/poFATxBAECmSd8V+f5ZhAA8QABAjulfED39+cQA3CAAYLbU3woRA3CDAICZ/DroPzwig" +
            "AsEAMxi8F8nBOCEAIAZDP77CQHivQkAaM/gf54QIJq/BQB9Gf7bsI5EcgIA/RhY23MaQBwBAH0Y/PsTA" +
            "sTwCAB6MPyPZb0ZzwnAPHYu8xhGa7z7PDGZAIC6DP71PBJgLI8AoCbDvxbXg3EEANRj2NTkujCKAIBaD" +
            "JnaXB/GEABQh+HSw7trxQQCANYzUHpyzWhNAMBahkhvrh9tCQBYx/CYwXWkJQEAaxgas7ietCMA4HiGx" +
            "UyuK60IADiWITGb60sbAgBgWyKAFvwtADjOxMGwxb+Rb2DCAgIAjjFhyO31B3Eu/Xe7r5e/JEh5AgD21" +
            "3mYrRpip//frusnAihNAMC+Og6vakOrcwyIAMryJUDg21eDYdXhNZ7zHQdKcgIA++ly4++4Q/1+zYYrP" +
            "MkJAOyjw2DquJs+1+VnECqUIwBge9Vv9hMG/7kOP5MIoBQBAFmmfyHNF+7gTgIAtlV1lzdx139N5Z/VK" +
            "QBlCACYL3VXLALgF34LALZT7cbuONxvC8BVTgBgG4Z/bdXWQ5CwnACAeQz/y6wLnBAA8LpKuzlD7neV1" +
            "scpAEsJAJjD8L+PdSLemwCAl1XZxRlqj6myXk4BWEYAQH+G/3OsG9EEADyvwu7NEHtNhfVzCsASAgD6M" +
            "vy3YR2JJADgOXZtbMn7icMJAOjJrnVb1pM4AgD6Maz2sXpdnQJwKAEAj1t5ozb892V9iSEAACCQAIDH2" +
            "P3Pt3KdPQbgMAIAejD8j2W9GU8AANTiFIBDCAC436obs93oGtad0QQAAAQSAADXOQVgLAEA93H8z5F8D" +
            "4DdCQCoy/CvwXVgJAEAAIEEAAAEEgBw24rnsY6da1lxPXwPgF0JAAAIJAAAIJAAgHoc/9fkujCKAACoy" +
            "/cA2I0AAIBAAgAAAgkA+N3RR7CeM9fm+jCGAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAgMf4VUBGE" +
            "AAAEEgAAEAgAQDX+UMswFgCAAACCQC4zpe9gLEEAAAEEgAAEEgAADzGl0MZQQAAQCABAACBBAAABBIAA" +
            "BBIAABAIAEAAIEEANTiV8xqc30YQwDA7/xzwMBIAgAAAgkAqMcxc00rrosTKHYjAAAgkAAAgEACAGryG" +
            "ADYlQCA2zyHxfN/xhEAABBIAEBdHgPU4DowkgCA+ziO5Ujeb+xOAEBtdp9rWX/GEgAAEEgAQH12ocDmB" +
            "ADcz3PZLKvCy/uMQwgA6MEpwLGsN+MJAAAIJADgMSuPZ+1Kj7FynR3/cxgBAACBBAA8zinAXNaXGAIA+" +
            "jGk9rF6XR3/cygBAD2JgG1ZT+IIAHiO3Rpb8n7icAIA+rJr3YZ1JJIAgOdV2LUZXq+psH52/ywhAKA/E" +
            "fAc60Y0AQCvqbJ7M8weU2W97P5ZRgDAHCLgPtaJeG8CADZRaRdnuP2u0vrY/bOUAIB5RMBlhj+cEACwj" +
            "Wo39Hch8H/WAi4QALCdiru69MFX8ee3+6cEAQDzpUZAevzArwQAbKvq7i7pGLzyz2r3TxkCALZX+SY/O" +
            "QQ864cHCADING1Qdvh57P4pRQDAPjrc7CfsmLv8DIY/5QgA2E+Xm37HEOj0mg1/SvrjsgB/Ox2ofqURh" +
            "nMCAPvquvurtMPu/KjC7p+ynADA/r4aD7BLr3vPoTZpl2/4U5oAgGN0joBzW0XB5CN9w5/yBAAcZ1IEn" +
            "PN8/h+GPy34DgAcy3CYzfWlDQEAxzMkgOUEAKwhAuZxTWlFAAC8zvCnHQEA6xgaM7iOtOS3AGCt7+HhW" +
            "/T9GPy05gQAajBMenG9aE8AQB2GSg+uEyMIAKjFcKnN9WEMAQD1GDI1uS6M4kuAUJMvB9Zh8DOSEwCoz" +
            "fBZy/ozlgCA+gyhNaw7o3kEAD14JHAcg58ITgCgF8NpX9aXGE4AoB+nAdsz+IkjAKAvIfA6g59YHgFAf" +
            "4bYc6wb0ZwAwAynw8yJwHWGPvxNAMA8Hg38m8EPZzwCgLm+DL7/sgZwgRMAmC/t8YCBD3cQAJBl8uMBg" +
            "x8eIAAg05RTAUMfniQAgPMhWjkIDHzYiAAAzlUKAgMfdiIAgFtuDeFXAsGAh0UEAPAqQxwa8u8AAEAgA" +
            "QAAgQQAAAQSAAAQSAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSA" +
            "AAQSAAAQCABAACBBMA87+kLAMBtAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAZvKrgAA/uS+eEQAAE" +
            "EgAAEAgATCX4y6A/3E/vEAAAEAgATCb6gXgIgEAwGQ2QlcIgPm8+YFU7n+/EAAAEEgAZFDBQBr3vRsEQ" +
            "A4fBiCF+90dBAAABBIAWVQxMJ373J0EQB4fDmAq97cHCIBMPiTANO5rDxIAuXxYgCncz54gALL50ADdu" +
            "Y89SQDw7gMENOXe9QIBwDcfJKALG5cNCABO+VAB1blHbUQAcIkPGFCNDcrG/oz6adjS9wfty6oCCxn6O" +
            "xEA3HL64RMDwBEM/QMIAB4hBoC9GPoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAPAAAAAAAA" +
            "AAAAAAAAAAAAKCQt7e3vwD7ygMVkMnQGAAAAABJRU5ErkJggg==")]
        public string imgObjetivo {
            get {
                return ((string)(this["imgObjetivo"]));
            }
        }
    }
}
